baseURL: "https://melgrejojesus.me"
languageCode: "en-us"
title: "Jesus Melgarejo"
theme: "./hugo-profile"
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true
params:
  version: 3

  favicon: "/images/icons_lemon.png"
  description: "Here it´s my professional portfolio, where you can find my personal skills and all projects I´ve done"

  # home
  disable_home: false
  profile_image: "/images/profile.png"
  name: "Jesús"
  profession: "Industrial Engineer"
  linkedin: "https://linkedin.com/in/jesusmelgarejoteruel"

  # About
  disable_about: false
  descripe_l1_person: "Hi, I'm Jesus, a passionate industrial engineer. I tend to learn about the use of modern technologies, 
  such as additive manufacturing, automatization and IoT, and apply them in the frame of production industry.
  "
  descripe_l2_person: "Interested in getting to know my profile more deeply? You can find my works [here](#projects)"
  skills:
    - name: SolidWorks
      percentage: 95
    - name: AutoCAD
      percentage: 85
    - name: 3D Printing
      percentage: 80
    - name: Python
      percentage: 70
    - name: IoT
      percentage: 50

  # Experience
  disable_experience: false
  experience:
    - company: "Technological Institute of Informatics"
      role: "Machine Learning Trainee Researcher"
      startdate: Jene 2021
      enddate: present
      featuredpoints: 
        - point: Development and testing of AI algorithms for the surface anomaly detection of objects with great variable textures, such as wood or metal.
        - point: Experimentation, investigation and discussion of alternatives.
        - point: Evaluation of the developed solutions.

  # Education
  disable_education: false
  education:
    - degree: "Degree"
      branch: "Mechanical Engineering"
      university: "Polytechnic University of Cartagena"
      startedyear: "2015"
      graduation: "2019"
    - degree: "Master"
      branch: "Industrial Engineering"
      university: "Polytechnic University of Valencia"
      startedyear: "2019"
      graduation: "present"

  # Projects
  disable_projects: false
  projects:
    - name: "Photovoltaic Canopy"
      img: /images/canopy.JPG
      description: "Nowadays, the use of renewable energies and electric vehicles has become 
        particularly relevant in order to lower the high pollution levels surrounding
        our cities. A photovoltaic canopy for charging electric 
        vehicles is a highly promising combination that can be set up in urban areas."
 
    - name: "Solar Tracker"
      img: /images/solar_tracker.JPG
      description: "Solar trackers are devices used to orient photovoltaic panels toward the sun. Since the sun’s position 
      in the sky changes with the seasons and the time of day, trackers are used to align the collection system to maximize
      energy production. "
      
    - name: "Speed Reducer Gear"
      img: /images/gear_reducer.jpg
      description: "A speed reducer is simply a gear train between the motor and the machinery that is used 
      to reduce the speed with which power is transmitted. This, particularly, is composed by 3 stages, one of them conical, which allows 
      to change the direction of the movement transmission."
      
  # Courses
  disable_achievements: false
  achievements:

    - title: Entrepreneurship in Circular Economy and Environment Course - COITIRM
      description: Introduction to circular economy, bussines models, digital marketing, legal and regulatory framework, financial plan and proyect management.
      img: /images/circular_economy.png
    - title: Python 3 Master Course - UDEMY
      description: Python fundamentals, optimization and data management, SQLite, Tkinter, Jupiter Notebook and advanced functionalities.
      img: /images/python_course.jpg
    - title: Digital Marketing Course - UDEMY
      description: Branding, web sites, email marketing, copywriting, SEO, google analatics and social media.
      img: /images/digital_marketing.jpg
    - title: 3D Printing and Modeling Course - UPCT
      description: Introduction to the basics of 3D printing and modeling.
      img: /images/3d_printing.jpg

  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "melgarejojesus97@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: false

  # Blog
  showdescription: false
  tweet: false